name: 'XPath Action'
description: 'Execute XPath 1.0 expression on a given document'
inputs:
  filename:
    description: 'The path to HTML or XML document'
    required: false 
  documentString: 
    description: 'HTML or XML string. Used instead of filename'
    required: false
  expression:
    description: 'XPath 1.0 expression'
    required: true
  namespaces:
    description: 'XML namespaces in JSON format'
    required: false
outputs:
  result:
    description: 'Evaluated items joined with a newline'
runs:
  using: 'node16'
  main: 'index.js'
