name: Test the action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v2

    - name: Execute xpath-action
      id: xpath
      uses: ./
      with:
        filename: ./.github/workflows/cd_catalog.xml
        expression: '//CD/YEAR/text()'

    - name: Get xpath result
      run: echo "Result from xpath-action:\n${{ steps.xpath.outputs.result }}"
